{"name": "test_m1", "status": "failed", "statusDetails": {"message": "AssertionError: test got failed\nassert (4 + 1) == 3", "trace": "def test_m1():\n        a=4\n        b=3\n>       assert a+1==b, \"test got failed\"\nE       AssertionError: test got failed\nE       assert (4 + 1) == 3\n\ntest_pytestbasics.py:6: AssertionError"}, "start": 1747369338013, "stop": 1747369338013, "uuid": "b87e8547-2d05-494c-9937-00b659791aad", "historyId": "f09aba8dd68675d3aff44528e90a0827", "testCaseId": "f09aba8dd68675d3aff44528e90a0827", "fullName": "test_pytestbasics#test_m1", "labels": [{"name": "suite", "value": "test_pytestbasics"}, {"name": "host", "value": "Madhu"}, {"name": "thread", "value": "30016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytestbasics"}]}